[book]
authors = ["ferrell-code"]
language = "en"
multilingual = false
src = "src"
title = "Pangaea"

[output.html]

default-theme = "light"
preferred-dark-theme = "light"
git-repository-url = "https://github.com/Pangaea-Network/Pangaea"
